 -- This file is a patch file generated by sync-diff-inspector
 -- Execute this file on the target database to fix the inconsistent data
 -- Table：schema3.table3
 -- Chunk range：id > 500 AND id < 800




 -- Source: schema3`.`table3` [`ID`:551] [`COL1`:2] [`COL3`:3]
 -- Target: schema3`.`table3` [`ID`:551] [`COL1`:2] [`COL3`:1]
 REPLACE INTO `schema3`.`table3` VALUES (551,2,3);

 -- Source: schema3`.`table3` [`ID`:552] [`COL1`:2] [`COL3`:3]
 -- Target: schema3`.`table3` [`ID`:552] [`COL1`:2] [`COL3`:1]
 REPLACE INTO `schema3`.`table3` VALUES (552,2,3);

 -- Source: schema3`.`table3` [`ID`:553] [`COL1`:2] [`COL3`:3]
 -- Target: schema3`.`table3` [`ID`:553] [`COL1`:2] [`COL3`:1]
 REPLACE INTO `schema3`.`table3` VALUES (553,2,3);

 -- Target: schema3`.`table3` [`ID`:665] [`COL1`:2] [`COL3`:1]
 DELETE FROM `schema3`.`table3` WHERE `ID` = 665 LIMIT 1;