 -- This file is a patch file generated by sync-diff-inspector
 -- Execute this file on the target database to fix the inconsistent data
 -- Table：schema3.table3
 -- Chunk range：id > 0 AND id < 500




 -- Source: schema3`.`table3` [`ID`:1] [`COL1`:2] [`COL3`:3]
 -- Target: schema3`.`table3` [`ID`:1] [`COL1`:2] [`COL3`:1]
 REPLACE INTO `schema3`.`table3` VALUES (1,2,3);

 -- Source: schema3`.`table3` [`ID`:2] [`COL1`:2] [`COL3`:3]
 -- Target: schema3`.`table3` [`ID`:2] [`COL1`:2] [`COL3`:1]
 REPLACE INTO `schema3`.`table3` VALUES (2,2,3);

 -- Source: schema3`.`table3` [`ID`:3] [`COL1`:2] [`COL3`:3]
 -- Target: schema3`.`table3` [`ID`:3] [`COL1`:2] [`COL3`:1]
 REPLACE INTO `schema3`.`table3` VALUES (3,2,3);

 -- Target: schema3`.`table3` [`ID`:5] [`COL1`:2] [`COL3`:1]
 DELETE FROM `schema3`.`table3` WHERE `ID` = 5 LIMIT 1;